### ISSUE TITLE
Photon perf links can be incorrect

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#103]
As described in here:
https://github.com/mozilla/firefox-health-dashboard/issues/99#issuecomment-396725435

**Comment by Mudra01** [comment]
I would like to work on this issue. As I am new to this platform could you brief me about this a bit.

**Comment by armenzg** [comment]
Sure! Have a look at https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/99#issuecomment-396725435 for more info. Load the health.graphics/quantum/64 page to see what it's meant.

**Comment by Mudra01** [comment]
I checked out the page as well as the comment. I still don't get the issue and the change I need to make. Could you explain it in a bit detail.

**Comment by armenzg** [comment]
Right now when we click on the header of one of the photon perf graphs we will get a link like this:
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=Median&arch=x86-64&cumulative=0&end_date=null&include_spill=0&keys=&max_channel_version=nightly%252F64&measure=FX_NEW_WINDOW_MS&min_channel_version=nightly%252F61&processType=*&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0

However, the link should look like this (processType=* --> processType=parent):
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=Median&arch=x86-64&cumulative=0&end_date=null&include_spill=0&keys=&max_channel_version=nightly%252F64&measure=FX_NEW_WINDOW_MS&min_channel_version=nightly%252F61&processType=parent&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0

Try to go through the code and see where that URL gets built.

**Comment by aimenbatool** [comment]
@sarah-clements Can you please explain this one too?

**Comment by sarah-clements** [comment]
> @sarah-clements Can you please explain this one too?

You'll need to change one of the query parameters from `processType=*` to `processType=parent` for all graph header links in the "Performance Metrics" section.

**Comment by aimenbatool** [comment]
Hi @sarah-clements, @djmitche  Maybe you can add something which I am missing to fix this. 

As per this https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/99#issuecomment-395867023 and the next one of Armen it looks like the fix is on the frontend. But based on my debugging i think it is something on backend. 

[This](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.jsx#L23) is the telemtryurl we are getting from the api and then [here](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/telemetry/graph.jsx#L74) it is setting to the graphTitleLink.

If we `console.log(telemetryUrl)` we get exact link building on the title (I checked through inspect element). But there is no `processType` parameter inside this link or on the title link. When we click on the link it then converts into another larger link and then we see a `processType` parameter inthe URL. 

How this URL is changing after clicking?

**Comment by sarah-clements** [comment]
Did you try doing what I suggested in my previous comment? The Telemetry frontend is setting a default because we don't currently add that query parameter to the url when it's being generated. If you go to the health dashboard and hover the mouse over one of the titles, you can see the that `processType=parent` is missing. So you'll need to figure out how to add it to the function that generates the link.
