### ISSUE TITLE
Update dashboard for new tp6-3, tp6-4, tp6-5, and tp6-6 suites

### ISSUE THREAD

**Issue by rwood-moz** [mozilla-frontend-infra/firefox-health-dashboard#204]
With Bug 1503990 we will be adding new Raptor tp6-3, tp6-4, tp6-5, and tp6-6 suites, each of which will be running on both Firefox and Chromium. Details:

raptor-tp6-3:
- [raptor-tp6-imdb-firefox]
- [raptor-tp6-imgur-firefox]
- [raptor-tp6-wikia-firefox]
- [raptor-tp6-imdb-chrome]
- [raptor-tp6-imgur-chrome]
- [raptor-tp6-wikia-chrome]

raptor-tp6-4:
- [raptor-tp6-bing-firefox]
- [raptor-tp6-yandex-firefox]
- [raptor-tp6-bing-chrome]
- [raptor-tp6-yandex-chrome]

raptor-tp6-5:
- [raptor-tp6-apple-firefox]
- [raptor-tp6-microsoft-firefox]
- [raptor-tp6-apple-chrome]
- [raptor-tp6-microsoft-chrome]

raptor-tp6-6:
- [raptor-tp6-reddit-firefox]
- [raptor-tp6-reddit-chrome]

If they could be added to the dashboard that would be appreciated, thank you kindly!

**Comment by klahnakoski** [comment]
I assume these should be added to "src/quantum/index-32bit.js" and its 64bit sibling.

Is there a logic behind the pairing I see in the chart layout?  For example **Tp6: Facebook** is beside **Tp6: Google**.  Or is being done instead of a flow layout? https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/index-32bit.js#L136..L187

**Comment by armenzg** [comment]
There's no specific logic behind the sorting.

**Comment by armenzg** [comment]
@klahnakoski let me know if you need another issue
