### ISSUE TITLE
Add ability to hide/show series on PerfherderGraphContainer

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#229]
This is a screenshot of what you can currently do in Perfherder:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/44410/49621829-25895280-f995-11e8-9591-ffbf98391131.png">

The checkbox allows removing data series as well as showing/hiding them.

**Comment by klahnakoski** [comment]
Some charting libraries do this by letting the user click on the legend.

**Comment by 2alin** [comment]
I think I can fix this.

**Comment by aimenbatool** [comment]
Hi @2alin, I'm glad that you solved this bug. On a lighter note, it was in my assigned tasks as a part of the internship. :-D 

You are going good! :)

**Comment by 2alin** [comment]
Thank you @aimenbatool, I hope there was no problem about taking the issue from your tasks, it wasn't intentional, I just saw it by chance, analyse it a little, decided that could be an easy but tricky fix, and went for it.
But don't worry, I'm still busy with the freaking custom tooltip, so I don't expect to take another one from your internship tasks, at least not soon :sweat_smile:.
