### ISSUE TITLE
Annotations for graphs

### ISSUE THREAD

**Issue by stuartphilp** [mozilla-frontend-infra/firefox-health-dashboard#23]
Each graph should have the ability to be annotated so we can add details/context around what a regression or improvement may be, and link out to a bug if there are relevant details.

**Comment by armenzg** [comment]
We can store data in a Postgresql table since we're already on Heroku.

The difficulty of this feature will depend on how we want to implement this.

If we want a tooltip when hovering over data points we will have to store the data point as a unique identifier for the annotation.
We will also need to select a data point in order to get a prompt into which to add the annotation.
We should also consider if we want to delete annotations via the UI or not.

If we have a widget somewhere around the graph containing all annotations sorted by date for such graph it will be easier.
To input an annotation we could have a button that triggers a modal prompt to select a data and a note.

How should we prevent this feature to be abused without authentication?

Should we also store who added the annotation and the date on which it got added? (If not necessary we can add it later).

Alternatively, we can store this data on a public spreadsheet that only certain people can modifiy it.

**Comment by armenzg** [comment]
Adding database support is not too complicated with knex. It is similar to Django with its migrations.
You can even have sqlite for local development while you can still have PostgreSql for production.
I will try to write a short blog post in the near future covering this topic, however, this is a longer tutorial where I learned from:
http://mherman.org/blog/2017/08/23/building-a-restful-api-with-koa-and-postgres/

The other component to this would be to restrict who can modify the entries on the database.
I believe this article would be sufficient, however, I've not completed it myself:
http://mherman.org/blog/2018/01/02/user-authentication-with-passport-and-koa/

**Comment by armenzg** [comment]
This is a feature that the devtools is interested on before migrating to arewefastyet.com.
I will file an issue once I process their requirements.

**Comment by armenzg** [comment]
We should look into integrating into Perfherder's alert system.

**Comment by armenzg** [comment]
This will be handled on #215
