### ISSUE TITLE
Switch Quantum Flow widget to BugzillaGraph (soon to be renamed)

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/firefox-health-dashboard#252]
Let's switch to the new component to plot [Bugzilla graphs](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/BugzillaBurndown/index.jsx
).
This can be configured like this:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/BugzillaBurndown/index.jsx

This will also help us move away from metrics-graphics toward chartJs.
As part of this we should also rename the component to BugzillaGraph.

Screenshot of the current look:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/44410/50773116-dc5f4380-125d-11e9-8e2c-89153b81ed0e.png">

Screenshot of what switching to ChartJs would look like:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/44410/50773301-7fb05880-125e-11e9-9d0c-63691cdf4ee7.png">

**Comment by aimenbatool** [comment]
>Let's switch to the new component to plot [Bugzilla graphs](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/BugzillaBurndown/index.jsx).
This can be configured like this:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/BugzillaBurndown/index.jsx

@sarah-clements link mentioned by Armen is now 
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/containers/BugzillaGraph/index.jsx
I didn't get the statement above. 

Also, In Quantum we have a [GraphContainer](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/index.jsx#L48)  component which is making map through a widget and we need to replace this with a [GraphJSWrapper](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/components/ChartJsWrapper/index.jsx) which is used by [this](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/quantum/index.jsx#L71) also. 

This is what i could understand by the given information. 

Can you please elaborte or correct if I am wrong?

**Comment by sarah-clements** [comment]
I think what he meant was that the quantumFlow graphs (in the Overview section for both `/quantum/32` and `/quantum/64` routes) are using the metrics-graphics library and he wants you to use the chartJS libary used by the `BugzillaGraph` instead. So you will need to figure out how to do that - use that entire `BugzillaGraphs` component (or refactor it so it can be used for the QuantumFlow graphs, and if it makes better sense to rename you could do that too), or just use the `ChartJSWrapper` in whatever component is being used for QuantumFlow.

Try to break down the task as best you can and if you get stuck, you can check in a WIP branch to ask for feedback. :)

**Comment by aimenbatool** [comment]
@sarah-clements I'm working on this one. I'm trying to refactor it but it looks like I am having challenges. Maybe a better start can help me.

**Comment by sarah-clements** [comment]
@aimenbatool I'm not sure what you're asking :)

**Comment by klahnakoski** [comment]
@aimenbatool I am guessing there is not refactoring", just making a whole new component to replace the existing chart.  Make a PR with your not-working attempts if you have a question.

**Comment by armenzg** [comment]
I've spoken with @jgong; let's kill the graph from the Quantum 32 & 64 pages.
It adds no value.

Let's remove [GraphContainer's code](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/components/graph-container.jsx) if it's not used anywhere else.

We might be able to get rid of `react-metrics-graphics` and other dependencies besides some other code in utils.

**Comment by klahnakoski** [comment]
We might consider subsuming this 

https://cpeterso.github.io/burndown/?since=2018-01-01&query_format=advanced&f1=OP&j1=AND&f2=OP&j2=OR&f3=bug_status&o3=equals&v3=NEW&f4=bug_status&o4=equals&v4=ASSIGNED&f5=bug_status&o5=equals&v5=UNCONFIRMED&f6=bug_status&o6=equals&v6=REPOENED&f7=bug_status&o7=anyexact&v7=RESOLVED%2CVERIFIED%2CCLOSED&n7=1&f8=CP&f9=status_whiteboard&o9=substring&v9=%5Bqf%3Ap1%3Apageload%5D&f10=component&o10=anyexact&v10=layout%3A+block+and+inline%2Ccss+parsing+and+computation%2Ccss+transitions+and+animations%2Cdom%3A+css+object+model%2Clayout%2Clayout%3A+block+and+Inline%2Clayout%3A+columns%2Clayout%3A+flexbox%2Clayout%3A+floats%2Clayout%3A+form+controls%2Clayout%3A+generated+content%2C+lists%2C+and+counters%2Clayout%3A+grid%2Clayout%3A+images%2C+video%2C+and+html+frames%2Clayout%3A+positioned%2Clayout%3A+ruby%2Clayout%3A+scrolling+and+overflow%2Clayout%3A+tables%2Clayout%3A+text+and+fonts%2Cprint+preview%2Cprinting%3A+output%2Cprinting%3A+setup%2C+svg&f11=CP

and this

https://charts.mozilla.org/quantum/p1.html

(takes a while to load)
