### ISSUE TITLE
Add hg and job link inside tooltip metadata

### ISSUE THREAD

**Issue by aimenbatool** [mozilla-frontend-infra/firefox-health-dashboard#303]
Please refer to this https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/213#issuecomment-462912268 for more details.

**Comment by 2alin** [comment]
I think the only way to get working links in the tooltip is creating a custom one through `options.tooltips.custom` which will allow any kind of html injection. But I'm afraid that if we decide to use them, we need create everything in the tooltip from scratch: style, position, html elements.

Is it the right path? @armenzg 

Have you made a significant progress on this one @aimenbatool? if you haven't I would like to work on it.

**Comment by aimenbatool** [comment]
@2alin Yes you are right. This needs a good refactoring to be converted into a custom tooltip as callbacks doesn't allow any HTML element inside it. And need to figure out a way to make this work with current flow. 

A solution is mentioned in the comment we need to find a way to implement. 

Armen is on leaves @sarah-clements  can add into it.

**Comment by 2alin** [comment]
Thank you @aimenbatool, 
after checking the past thread and the gist you shared, I concur with the way you built `hgLink`

```https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=${prevRevision}&tochange=${currRevision}```

but I think you missed a querry, building  `jobLink`, instead of

```https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=ca0f00593e38cdab54c3a990059bbf1150e77365&selectedJob=${tooltipDataSet.job_id}&group_state=expanded```

it should be

```https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=${currRevision}&selectedJob=${tooltipDataSet.job_id}&group_state=expanded```

with `currRevision` initialization position adjusted as well (from line 42 to <39).

Also, @armenzg was asking in the thread for the a 'link to compare', which, if I'm not wrong, should be generated like this:

```https://treeherder.mozilla.org/perf.html#/comparesubtest?originalProject=mozilla-central&newProject=mozilla-central&originalRevision=${prevRevision}&newRevision=${currRevision}&originalSignature=${prevSignatureID}&newSignature=${currSignatureID}&framework=10```

with the new required values calculated as well.

**Comment by 2alin** [comment]
If there's no problem then @aimenbatool I'll take this issue and create the custom tooltips from scratch and use the code you had made to calculate the values we need to display.

Or if you prefer we can work together creating the custom tooltip, it will be a lot of work and I would be happy to share duties :grinning:. I'm also a newbie in web dev and I'm planning to participate in the next outreachy internship program like you did. Your story in medium inspired me a lot :sunglasses:.

**Comment by aimenbatool** [comment]
Hi, @2alin I have published the updated gist. 
>it should be

`https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=${currRevision}&selectedJob=${tooltipDataSet.job_id}&group_state=expanded`

as per Armen's comment it should be the `prevRevision`. [1]

You can work on this issue and i will help and give my input whereever possible. 

Good luck for your Outreachy application. I'm not sure if this project is listed again in Outreachy or not. But you will have to contribute to the projects listed on Outreachy website. You are welcome to contribute here but if you want to do it for Outreachy then make sure you are contributing to the right project to get selected. 

[1]
<img width="694" alt="screen shot 2019-02-18 at 5 00 18 pm" src="https://user-images.githubusercontent.com/13648547/52949715-e1f09300-339e-11e9-96b2-7597d2ca69b7.png">

**Comment by sarah-clements** [comment]
@2alin Please assign yourself to this issue if you are working on it.

**Comment by 2alin** [comment]
@sarah-clements  Yup, I'm working already on it. Thank you!

@aimenbatool I think there's a little confusion there with the links used in Armen's post: yes you are right just checking what you highlighted with colors means that `prevRevision`should be used **but** he could have misused a different link because if you go [here](https://treeherder.mozilla.org/perf.html#/graphs?series=mozilla-central,1776360,1,10&series=mozilla-central,1775979,1,10&series=mozilla-central,1776166,1,10&selected=mozilla-central,1776166,413555,667080523,10) and compare the queries in the links for _Job_ and _Hg_, you'll notice that `currRevision` is used [1]. What do you think?

![prev-curr-revision-links](https://user-images.githubusercontent.com/4089035/52971518-53b7e500-337d-11e9-9328-cf22b68384b3.png)

And thank you for your wishes about outreachy, yup probably this repo won't be listed there (checking it today), but i wanted to be involved in it anyway :grin:

**Comment by djmitche** [comment]
> @2alin Please assign yourself to this issue if you are working on it.

People who aren't project participants can't assign issues, and even admins can't assign things to non-participants :(

**Comment by klahnakoski** [comment]
@djmitche yes, I can not assign @2alin either  :/

**Comment by 2alin** [comment]
Hi there, just to update you all with I have accomplished so far about this issue. The custom tooltip already:

:heavy_check_mark: accepts `<a>` elements that takes them from `tooltip.footer` but it could  take from `tooltip.title` or `tooltip.body`, it doesn't matter (the 'mozilla' text in the video [1] is a test link). 
:heavy_check_mark: been styled to resemble the normal tooltips. 
:heavy_check_mark: been made dynamic about their y-position [1] (again, like nomal tooltips). In all the code examples I saw for custom tooltips the position was fixed _under_ the data point, but for our case that was a problem because, with the plots at the bottom, the tooltip went out of vertical range and forced the document's height to increase.

and what's left:

:exclamation: handle `onClick`events over the datapoint. At the moment (due to being a custom) the tooltip can't stay visible when the pointer is moved out from the datapoint and that makes impossible to click over any link there, which is pretty bad. I already know how to do it.

Now I have some questions, @aimenbatool @klahnakoski:

1. The function that generates the tooltip (`generateCustomTooltip`), where should I put it? a the moment I'm exporting it from `src/utils/chartJs/generateCustomTooltip.js`, is it right? Have in mind that it's called from `perfherderFormatter.js` > `tooltips.custom`, but because `generateCustomTooltip` is already big (around 100 lines) I decided to import it from an external file.

2. The custom tooltip is rendered as an HTML element, so it needs its own style (around 28 lines of code) for all the elements inside of it. Just for testing purposes I'm adding the style right into `/src/index.css` but something tells me that is so wrong :sweat_smile:. I could add it as inline style in the same `generateCustomTooltip.js` but for that many lines of style it will be a pain in the a$$. Where should I put the style for the custom tooltip?

And well, I'll have more decision-making questions once I work with what's left. But for now, these are enough.

[1] custom tooltip so far:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4089035/53153134-26398a00-357d-11e9-89bc-ca4cd5eb5488.gif)

**Comment by klahnakoski** [comment]
Please make a PR, and prefix the title with "WIP: " (for Work In Progress". This will allow us to add comments to (broken) code, and be more specific about our suggestions.  The `--no-verify` flag works on commits and pushes to let you do that.

1. The custom tooltip should have two parts:  A component (a function really) that declares what the tip looks like, and a bundle of code that gets it to work with chartJS.  The former belongs to the dashboard showing the chart, so put it in utils.  The latter belongs near the ChartJS wrapper.
2. The styling should be in the component.  [here is an example](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/components/ChartJsWrapper/index.jsx#L9), and notice at the end there is a `withStyles` high level component that uses it.  The hope is we can remove the CSS file for most everything.

**Comment by klahnakoski** [comment]
Not part of this PR, but highly related: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/215

**Comment by aimenbatool** [comment]
@2alin I'm glad that you figured out adding a link into the tooltip. I'm wondering if we are able to add the link (Mozilla link in your video) with a title or body why don't we go with this and refactor code to put data into a tooltip body instead of the footer? If we do this, do we still need to have a custom tooltip?

I agree with Ekyle, `customTooltip` should go inside the utils folder, as we already have [registerTooltip](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/registerTooltip.jsx) functionality here.

Regarding css, go with what Ekyle says, as we are using JSS (CSS in JS) to apply CSS and this technique is used throughout the project. You might want to read about this [more in detail](https://material-ui.com/customization/css-in-js/). 

Making a PR would be helpful for us to review and specially for me to learn what you do with this customToolTip. 
You are giong good. 👍

**Comment by 2alin** [comment]
@klahnakoski:
>   1.The custom tooltip should have two parts:  A component (a function really) that declares what the tip looks like, and a bundle of code that gets it to work with chartJS.

I think I got your idea, but I need to analyse what you said carefully in order to implement it. At the moment I have `generateCustomTooltip` as this gist [[1]](https://gist.github.com/2alin/12abc8dd1ae9c92d0e7d82f03899b6b1) (without the css needed), but I'll need to convert it to a react component in order to use `withStyles`, also I need to fix the errors for using `this._chart` and other warnings.

> Please make a PR, and prefix the title with "WIP: "

Yup, once I implement it as you suggested before, or if I get stuck for too much time, I'll make a PR :)  

---

@aimenbatool: 

>  I'm wondering if we are able to add the link (Mozilla link in your video) with a title or body why don't we go with this and refactor code to put data into a tooltip body instead of the footer?

I was going to suggest that in the future, I think  some of the data in the `tooltip.footer` should go to into the `tooltip.body` for semantic purposes. But that can be discussed later on when the custom tooltip is working properly.

> If we do this, do we still need to have a custom tooltip?

Yes we need it anyway: There are two tooltips, the 'canvas tooltip' that's generated by chartjs and uses the `tooltip` object that contains all needed data (body, footer, position, etc), and the 'custom tooltip' that we are creating as an html element and who is using the same `tooltip` object to get the data needed. What we are doing under the hood is disabling the 'canvas tooltip' and hook the `tooltip` object with 'custom tooltip' in order to render whatever is stored there (including links).

> as we already have [registerTooltip](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/registerTooltip.jsx) functionality here.

Thank youuu, aimen!!! just checking the code there already show me how to solve some freaking warnings I was getting. And as I mentioned before, yup I'll open a PR, but meanwhile you can check there code in the gist I shared with kyle [[1]](https://gist.github.com/2alin/12abc8dd1ae9c92d0e7d82f03899b6b1)

---

[1]
https://gist.github.com/2alin/12abc8dd1ae9c92d0e7d82f03899b6b1

**Comment by klahnakoski** [comment]
https://www.chartjs.org/docs/latest/configuration/tooltip.html#external-custom-tooltips

**Comment by klahnakoski** [comment]
From that link I am guessing you should [make a React function](https://reactjs.org/docs/components-and-props.html) that accepts the `tooltipModel` object as a parameter.  Injecting it into the chart involves setting the `options.tooltips.custom` to that function.

From the link above:

```js
var myPieChart = new Chart(ctx, {
    type: 'pie',
    data: data,
    options: {
        tooltips: {
            // Disable the on-canvas tooltip
            enabled: false,

            custom: function(tooltipModel) {

```

**Comment by klahnakoski** [comment]
the function in the docs is a bad example.  Using JSX, React and `withStyles` will make nicer looking code.

**Comment by 2alin** [comment]
yup, I noticed the different approaches since your first suggestion at the top, and I get the idea of using using instead react components and receiving the `tooltip`(tooltipModel) as a prop, in fact that's the only way if we want to use `withStyles` which also is the cleanest way in order to style the tooltip, so it's all chained up . Thank you both, kyle/aimen, for your comments and suggestions, they were very helpful. I'll implement what was said before and push a partial PR after that.
