### ISSUE TITLE
improve README.md with better setup instructions

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#332]
The readme could benefit from better instructions

* how to tell which verison of node/yarn you have
* how to run tests, hos to update them
* what IDE (and plugins) to use while developing
* move the [Making Changes....](https://github.com/mozilla-frontend-infra/firefox-health-dashboard#making-changes-to-a-page) to another doc

**Comment by aimenbatool** [comment]
What do you mean by 'development details'? This https://github.com/mozilla-frontend-infra/firefox-health-dashboard#building ?

**Comment by klahnakoski** [comment]
@aimenbatool updated first comment

**Comment by armenzg** [comment]
Would you like to add some of that to this repo?
https://github.com/armenzg/webdev-guide

We can then point this repo to the guide I'm working on.

**Comment by cassyblaise** [comment]
@klahnakoski hey,
I am a new contributor and an outreachy applicant, Can I try working on this issue, if it's available?

**Comment by aimenbatool** [comment]
@cassyblaise go ahead and open a PR. @klahnakoski is away may be.

**Comment by klahnakoski** [comment]
@cassyblaise if you find the documentation is missing something, then yes please add to it.  If you followed the instructions and everything is running fine for you then please skip this: It is already good enough.

**Comment by klahnakoski** [comment]
@armenzg  Yes, a more general webdev guide may help here; although we differ on where it belongs: There should be a repo that can be used to launch a fresh dashboard; and that repo would have a `/docs` directory with these general instructions for webdev.

**Comment by aimenbatool** [comment]
@armenzg, @klahnakoski Hi,
When I wrote an article about firefox-health dashboard we talked (on call) about putting some content in the README.md file. 

When I was starting on this project I was barely able to understand the technical information provided on the README file. Like there is mentioned how to change things and make code changes but no information provided on what these terms (Perfherder, Bugzilla, Telemetry, etc.) are for.

So improving technical details of the README.md is in my mind since a long time. I need your thoughts how can we improve it? Or do you think is there any need of doing this or its just me? 

If yes, we can open an other discussion issue to keep basic improvements changes in this issue for beginners.

Article: https://medium.freecodecamp.org/here-is-how-we-take-care-of-firefox-health-at-mozilla-8f7f9b085955

**Comment by armenzg** [comment]
I will let @klahnakoski follow up on this.

My two cents would be to point to blog posts or documentation explaining what each of those are.
For instance:
https://wiki.mozilla.org/EngineeringProductivity/Projects/Perfherder
https://bmo.readthedocs.io/en/latest/about/index.html

**Comment by klahnakoski** [comment]
@aimenbatool   Feel free to add what you think is missing. You know best.  At the very least add links to information you think was **useful**.  Adding a short description of Perfherder, Bugzilla and Telemetry under definitions would help a lot.  Links to docs, like the ones Armen pointed to, are best added to the footer since they are good for reference, but too verbose for this project.

**Comment by aimenbatool** [comment]
@klahnakoski Perfect. I will start working on it v soon.
