### ISSUE TITLE
click-lock is not working on new tooltip

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#372]
as per

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/361#issuecomment-477944311

some code involving clicking can be found here:

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/utils/registerTooltip.jsx

**Comment by 2alin** [comment]
Yup, thank you @klahnakoski. I'll work on this today.

**Comment by 2alin** [comment]
**update**: 
Unfortunately,`registerTooltip`creates a new instance of the default chartjs tooltip class in the last datapoint clicked, and that procedure and environment can't be used for our custom tooltip, not without getting super messy.
I'll rather fix this handling 'click' events over the charts and behave properly when there's already a tooltip displayed. Just one thing, instead of passing 'onClick' events to `<ChartJsWrapper/>` and all the way to `<Chart/>`, I'll attach the 'onClick' handler to one of the `options.onClick, which is the way ChartJs handle such events.
