### ISSUE TITLE
Display Chrome v72 power usage test results

### ISSUE THREAD

**Issue by davehunt** [mozilla-frontend-infra/firefox-health-dashboard#475]
Show results from the one-off run of power usage against Chrome v72 in the idle and idle-background graphs.

* Foreground idle results for Chrome v72 can be found here: https://drive.google.com/drive/folders/10cwkTFFNPKl49gaKfFpnVH79MbpnEApf
* Background idle results for Chrome v72 can be found here: https://drive.google.com/drive/folders/1Y3s_66YZk-4nK1NT9ZdX5Yr6jI5ARMb6

**Comment by davehunt** [comment]
New results have been gathered, which can be found here: https://drive.google.com/drive/folders/1OoruoDks5MvGOul7j7xniCiy_eC5d0Gg

**Comment by klahnakoski** [comment]
These results will require some expertise to digest:  The first step is generating something simpler, a list of `{browser, suite, platform, value}` tuples.

**Comment by klahnakoski** [comment]
@gmierz  this is a reminder to provide us with something simpler.

**Comment by gmierz** [comment]
Apologies for the delay! I think we have some issues with the data...

For geckoview browser in the data we've collected - the cpu value is much lower than it should be (expected to be in the 10's), and the screen power is also lower by about 20 mAh:
```
Formatted values for cpu: ['Geckoview', 'raptor-scn-power-idle', 'MotoG5', 0.9013333333333334]
Formatted values for wifi: ['Geckoview', 'raptor-scn-power-idle', 'MotoG5', 0.1024]
Formatted values for screen: ['Geckoview', 'raptor-scn-power-idle', 'MotoG5', 51.333333333333336]
```

For chrome, it's hard to compare to CI data, but for moto G5 there shouldn't be much difference in screen power usage from one app to another, so it is working. But the low values elsewhere suggest that we had an issue with device configuration in this data:
```
Formatted values for cpu: ['Google Chrome', 'raptor-scn-power-idle', 'MotoG5', 0.01056]
Formatted values for wifi: ['Google Chrome', 'raptor-scn-power-idle', 'MotoG5', 0.10266666666666667]
Formatted values for screen: ['Google Chrome', 'raptor-scn-power-idle', 'MotoG5', 48.76]
```

This data (for geckoview at least) doesn't agree with the data we have on health graphics at the moment, but it should to an extent.

@klahnakoski I don't think we should add this data because of these issues. I am wondering what @davehunt thinks we should do. We can either (i) redo the tests with a device that is known to work, or (ii) wait until we have chrome available on the CI devices and report those values.

**Comment by davehunt** [comment]
Can we try repeating the test to see if the data is closer to what we're expecting? If we experience similar issues again then it may be worth waiting until we can do this in CI (this will depend on us moving to browsertime).

**Comment by klahnakoski** [comment]
@davehunt @gmierz @airimovici  Do we have this number yet?  Please provide a link

**Comment by davehunt** [comment]
I'm going to close this as it's no longer a priority. Fenix release criteria is currently measuring against Fennec v68.
