### ISSUE TITLE
GeckoView power-use data is missing for 10+ days

### ISSUE THREAD

**Issue by stephendonner** [mozilla-frontend-infra/firefox-health-dashboard#543]
https://health.graphics/android links to GeckoView's https://health.graphics/power?browser=geckoview&suite=speedometer&past=month&ending=2019-09-04, which has had missing data for over 10 days.

https://health.graphics/power?browser=geckoview&suite=scn-power-idle-bg&past=week&ending=2019-09-04 and https://health.graphics/power?browser=geckoview&suite=scn-power-idle&past=2day&ending=2019-09-04 are also missing data.

It's late for me tonight, but I'll also look into this tomorrow, and see if it's a naming issue, etc.

/cc @davehunt and @gmierz

**Comment by gmierz** [comment]
This was fixed by the following PR: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/540

The issue for it was here: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/532

I can't close this bug so if someone else could that would be great (@klahnakoski?).
