### ISSUE TITLE
remove fennec v64 as a comparison point on health.graphics

### ISSUE THREAD

**Issue by bebef1987** [mozilla-frontend-infra/firefox-health-dashboard#567]
As we will remove all Fennec tests(Except for the Fennec ESR 68) we need to remove this comparison from health graphics

**Comment by davehunt** [comment]
I know enhancements to this only recently landed, but it's unlikely that Fennec v64 will be used as a comparison point in the future. We should remove this target in tha page load visualisations.

**Comment by klahnakoski** [comment]
This just landed.  Is there some other reference we will use instead?

**Comment by davehunt** [comment]
@klahnakoski Fenix 1.0 had release criteria that was relative to Fennec v64 performance. There is a chance that future release criteria will be set, however it's unlikely that this will be against Fennec v64. We are going to run against Fennec ESR68 on a weekly basis, so I did propose comparing with that, but it was decided that it would be best to remove this target entirely for now.

Sorry for the recent effort you put into this, I should have reassessed the priority of this since we shipped Fenix 1.0.
