### ISSUE TITLE
Show results on playback-summary for >1080p H264 encoded videos

### ISSUE THREAD

**Issue by airimovici** [mozilla-frontend-infra/firefox-health-dashboard#569]
There are no video tests for H264 encoded videos >1080p with 60 frames (for any browser on any platform) as you can see here(the page used for running the tests): https://yttest.prod.mozaws.net/2019/main.html?test_type=playbackperf-test&raptor=true&command=run&exclude=1,2&muted=true

https://health.graphics/playback/details?platform=win-aarch64&browser=firefox&encoding=H264&past=week&ending=2019-09-24

For the playback summaries, we still take into account the potential dropped frames we have for 2160p60 videos with H264 encoding (that don't exist), so we never show data for them:

![playback-summary-page](https://user-images.githubusercontent.com/51707553/65526624-165e9b80-defa-11e9-99b1-eea7247d931d.png)

**Comment by airimovici** [comment]
@davehunt @klahnakoski I added this separate issue with this problem that I could not solve in the [media summary page PR](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/563)

**Comment by klahnakoski** [comment]
This is best answered by whoever is using these grids.  My naive opinion is to ensure the columns are the same for both encodings so they are easier to visually compare.

I choose to show results for only 60frames/second to keep the overall view simple, and maximize the number of frames dropped (more likely on the 60 rather than the 30).  Maybe the grid will not be confusing if we show 30frames/second when 60frames/second is not available?  Although we do loose the fact we are not running 60frames/second, which may be relevant.

**Comment by klahnakoski** [comment]
I will note that the grid is much easier to read, and it does highlight the frame rates not tested on any browser/platform. This could be considered a feature, compared to the test summary link (https://yttest.prod.mozaws.net/2019/main.html?test_type=playbackperf-test&raptor=true&command=run&exclude=1,2&muted=true), which is a difficult read.

**Comment by airimovici** [comment]
@klahnakoski  I agree, it would be confusing to have the summary for 30 frames/sec for one encoding and 60 frames/sec for another.

Like you said, it's best to know if the data that we ignore for H264 30f/sec videos is useful for people that use the summaries.

**Comment by klahnakoski** [comment]
I am closing this.  We have added new criterion for 30fps, and these charts should be showing the 30fps criterion in the tooltip.  If something needs to change, then make a new issue.
