### ISSUE TITLE
Add speedIndex test results

### ISSUE THREAD

**Issue by airimovici** [mozilla-frontend-infra/firefox-health-dashboard#663]
Add results in Android page, `Raptor (TP6m)` section, similar to the existing graphs.
Detailed results should appear under tp6m: https://health.graphics/android/tp6m?test=cold-loadtime&browserPlatform=fenix-g5&past=month&ending=2020-02-13
Rename framework names (like `raptor`) - ex: Raptor (TP6m) -> “Page load”

**Comment by sabina-rohman** [comment]
Hi, @airimovici  I'm an outreachy applicant May 2020. Can I please work on this issue, if it's still open?

**Comment by kimberlythegeek** [comment]
Hi @sabina-rohman! I am one of the mentors for the intern project. I have reached out to Alex to see if he is still working on this, if not, I can assign you. Feel free to ping me with any questions you may have. You can also make contributions to Perfherder, another react dashboard. This is outside the scope of the internship, but there are many more issues available to work on. 

https://bugzilla.mozilla.org/buglist.cgi?product=Tree%20Management&component=Perfherder&resolution=---&list_id=15132483

**Comment by sabina-rohman** [comment]
Hi @kimberlythegeek Thanks. Feel free to assign the issue to me, if @airimovici isn't still working on this.
In the meantime I will go ahead and look at  Perfherder. :)

**Comment by airimovici** [comment]
I'm not working on it, @kimberlythegeek @sabina-rohman. I'm assigning this to you

**Comment by kimberlythegeek** [comment]
thanks @airimovici !

**Comment by sabina-rohman** [comment]
Thanks @airimovici :)

**Comment by lorelajano** [comment]
Hello @kimberlythegeek . I am an outreachy applicant. Please can you suggest me an issue to start my contribution? Thank you

**Comment by kimberlythegeek** [comment]
@lorelajano Hi there--we do not have many open issues for this project, but we are also accepting contributons to Perfherder, another react dashboard. The issues for this are managed on Bugzilla

[Bugzilla User Guide](https://bugzilla.readthedocs.io/en/latest/using/)

[Perfherder bugs](https://bugzilla.mozilla.org/buglist.cgi?cmdtype=runnamed&namedcmd=Perfherder%20Unassigned&list_id=15152567)

On bugzilla, please :needinfo me, otherwise I will not get a notification that there is a comment on the bug. You can do this by checking the box at the bottom of the page that says “Request info from” and then type in my email: ksereduck@mozilla.com

**Comment by airimovici** [comment]
Closing this. Work will continue here: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/704
