### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by sarah-clements** [mozilla-frontend-infra/firefox-health-dashboard#83]
For all of the Quantum routes and crashes/beta (and possibly others?), if an endpoint fails the page continues to show "loading" indefinitely.

**Comment by sarah-clements** [comment]
It would also be a good idea to add error handling that informs the user that they failed to enter required query parameters.

**Comment by aimenbatool** [comment]
@sarah-clements Can you show how to reproduce the error to see what need to be fixed and where?
Please explain this.

**Comment by sarah-clements** [comment]
[These](https://github.com/mozilla-frontend-infra/firefox-health-dashboard/blob/master/src/routes.jsx) are the routes I was referring to. So as an example, if I type something incorrectly [here](https://health.graphics/quantum/64/kraken), the page only shows 'loading' instead of a useful error message that my query parameters are wrong and what I need to supply. This would be for the route '/quantum/:platform/:suite' with `platform` and `suite` being query parameters (this might be different from what you've seen, ex: `platform=64`, that can be done with[ react-router](https://reacttraining.com/react-router/web/guides/philosophy)). 

With that being said, since I filed this bug almost a year ago and I don't know all that has changed within this app, it'd be worth checking with @klahnakoski and coordinating with him on what else might need useful error handling either from lack of query parameters or from API's failing. If the issue has already been solved in different ways, you can post a short explanation and close out the bug.

**Comment by klahnakoski** [comment]
@aimenbatool 

The problem is best seen here https://health.graphics/quantum/64

Open the debugger and watch the network requests.  There are many telemetry requests, and some always fail.  It would be nice to have the chart space filled with some indication that it failed.

The telemetry charts are still using the old school metrics graphics and are not wrapped with any "loading" indicator. I do not suggest you replace them with ChartJS versions, instead. "just" wrap them in loading/error indicators.

On the subject of "wrapping them with loading/error indicators". I realize we do not have a function for that yet.  You will notice that we have lots of switching code. Here is one example:

```js
  return data ? (
    <div className={classes.chartContainer}>
      {showError && (
        <ErrorPanel
          className={classes.errorPanel}
          error="This item has been missing data for at least 3 days."
        />
      )}
      {title && <h2>{title}</h2>}
      <Chart
        type={type}
        data={data}
        height={chartHeight}
        options={generateOptions(options)}
      />
    </div>
  ) : (
    <div
      style={{
        lineHeight: spinnerSize,
        textAlign: 'center',
        width: spinnerSize,
      }}>
      <CircularProgress />
    </div>
  );
```

The `data` and `showError` are checked for three possible display states. This logic is too convoluted for the simple thing it does.  When making loading or error components, please make them higher order components (HOCs) that take the primary component (in this case the chart) and wraps it, so the code looks something like:


```js
    return <div className={classes.chartContainer}>
      {title && <h2>{title}</h2>}
      <Chart
        type={type}
        data={data}
        height={chartHeight}
        options={generateOptions(options)}
      />
    </div>
  );
```
and the export line do the wrapping

```js
export default withStyles(styles)(
    withError(errorParam)(
        withLoading(loadParam)(
            ChartJsWrapper
        )
    )
);
```

maybe we can chain these HOCs

```js
export default with(ChartJSWrapper)
    .withError(errorParam)
    .withLoading(loadParam)
    .withStyles(styles);
```

**Comment by klahnakoski** [comment]
Doh! I got sidetracked on Component loading, rather than full page loading.  Give me a moment to give an example of that.

**Comment by klahnakoski** [comment]
Here are invalid URLS that should error out

https://health.graphics/quantum/tp6?bits=63

https://health.graphics/quantum/323

You can see the loading chart icon when you run the health graphics from your local dev environment and your network is cut off (so you can not get to Treeherder)

http://localhost:5000/quantum/tp6?bits=64

![image](https://user-images.githubusercontent.com/2334429/52757405-87d48400-2fd2-11e9-983e-0b55b246d724.png)

![image](https://user-images.githubusercontent.com/2334429/52757377-71c6c380-2fd2-11e9-94ea-9dd2e7fd0c15.png)

**Comment by sarah-clements** [comment]
@aimenbatool I think you could also start with adding the ErrorPanel (and keep the loading indicators as a separate component or a separate problem to be solved later) to the Graph containers for when individual APIs fail. If you wanted to try the HOC approach, I'd suggest starting with one aspect at a time - such as the error handling.
